#! /usr/bin/python3

import sys
import os
from collections import defaultdict

if len(sys.argv) < 3:
    print("usage: cover_reachables.py <global_reachables_file> <reachables_by_vp_dir>")
    exit()

global_reach_file = sys.argv[1]
reachables_by_vp_dir = os.path.abspath(sys.argv[2])

uncovered_reachables = set()
with open(global_reach_file, 'r') as f:
    for line in f:
        uncovered_reachables.add(line.strip())
tot = len(uncovered_reachables)


reachables_by_vp = defaultdict(set)
for vp_name in os.listdir(reachables_by_vp_dir):
    with open(os.path.join(reachables_by_vp_dir, vp_name), 'r') as f:
        for line in f:
            chunks = line.strip().split(',')
            reachables_by_vp[vp_name].add(chunks[1])

print("#VP Chosen\tNumber Reachable Destinations Covered\tFraction of Reachable Destinations Covered\tCumulative Fraction of Reachable Destinations Covered")
frac = 0.0
cumfrac = 0.0
num_covered = 1
while len(uncovered_reachables) > 0 and num_covered > 0 and\
        len(reachables_by_vp) > 0:
    num_covered = 0
    max_covered = 0
    chosen_vp = ""
    for vp, dsts in reachables_by_vp.items():
        num_covered = len(uncovered_reachables & dsts)
        if num_covered > max_covered:
            chosen_vp = vp
            max_covered = num_covered
    uncovered_reachables -= reachables_by_vp[chosen_vp]
    frac = float(max_covered)/tot
    cumfrac += frac
    del reachables_by_vp[chosen_vp]
    print("%s\t%d\t%f\t%f" % (chosen_vp, max_covered, frac, cumfrac))
