#! /bin/bash

probe_dir=$1
train_dir=$2
results_dir=$3
ipasn_file=$4

echo making output dir...
mkdir -p $results_dir
mkdir -p $results_dir/destination_cover/asn
mkdir -p $results_dir/destination_cover/bgp
mkdir -p $results_dir/destination_cover/s24

mkdir -p $results_dir/ingress_cover/asn
mkdir -p $results_dir/ingress_cover/bgp
mkdir -p $results_dir/ingress_cover/s24

echo generating set cover rankings
./rank_vps_set_cover $probe_dir > $results_dir/set_cover_rankings.txt &

echo making destination cover data...
dbd_asn=$results_dir/destination_cover/asn/dests_by_dnet.pickle
dbd_bgp=$results_dir/destination_cover/bgp/dests_by_dnet.pickle
dbd_s24=$results_dir/destination_cover/s24/dests_by_dnet.pickle

./make_dests_by_dnet $train_dir/asn $dbd_asn &
./make_dests_by_dnet $train_dir/prefix $dbd_bgp &
./make_dests_by_dnet $train_dir/s24 $dbd_s24
echo done

echo making ingress cover data...
ingr_asn=$results_dir/ingress_cover/asn/vp_dists_by_ingr_by_dnet.json
ingr_bgp=$results_dir/ingress_cover/bgp/vp_dists_by_ingr_by_dnet.json
ingr_s24=$results_dir/ingress_cover/s24/vp_dists_by_ingr_by_dnet.json

./rank_vps_ingress_cover $train_dir/asn asn $ingr_asn $ipasn_file &
./rank_vps_ingress_cover $train_dir/prefix bgp $ingr_bgp $ipasn_file &
./rank_vps_ingress_cover $train_dir/s24 24 $ingr_s24
echo done

echo making destination cover rankings...
dc_asn=$results_dir/destination_cover/asn/rankings_by_dnet.csv
dc_bgp=$results_dir/destination_cover/bgp/rankings_by_dnet.csv
dc_s24=$results_dir/destination_cover/s24/rankings_by_dnet.csv

./rank_vps_destination_cover $dbd_asn $train_dir/asn > $dc_asn &
./rank_vps_destination_cover $dbd_bgp $train_dir/prefix > $dc_bgp &
./rank_vps_destination_cover $dbd_s24 $train_dir/s24 > $dc_s24 &
echo done


echo making ingress cover rankings...
./aggregate_ingresses_and_rank $ingr_asn $results_dir/ingress_cover/asn/rankings_by_dnet.csv &
./aggregate_ingresses_and_rank $ingr_bgp $results_dir/ingress_cover/bgp/rankings_by_dnet.csv &
./aggregate_ingresses_and_rank $ingr_s24 $results_dir/ingress_cover/s24/rankings_by_dnet.csv
echo done
